# Data Description

In this dataset, you will find a refactorised version of the data from the London data store, that contains the energy consumption readings for a sample of 5,567 London Households that took part in the UK Power Networks led Low Carbon London project between November 2011 and February 2014. The data from the smart meters seems associated only to the electrical consumption.

There is 19 files in this dataset :

informations_households.csv : this file that contains all the information on the households in the panel (their acorn group, their tariff) and in which block.csv.gz file their data are stored

halfhourly_dataset.zip: Zip file that contains the block files with the half-hourly smart meter measurement

daily_dataset.zip: Zip file that contains the block files with the daily information like the number of measures, minimum, maximum, mean, median, sum and std.

acorn_details.csv : Details on the acorn groups and their profile of the people in the group, it's come from this xlsx spreadsheet.The first three columns are the attributes studied, the ACORN-X is the index of the attribute. At a national scale, the index is 100 if for one column the value is 150 it means that there are 1.5 times more people with this attribute in the ACORN group than at the national scale. You can find an explanation on the CACI website

weather_daily_darksky.csv : that contains the daily data from darksky api. You can find more details about the parameters in the documentation of the api

weather_hourly_darksky.csv : that contains the hourly data from darksky api. You can find more details about the parameters in the documentation of the api

Inspiration
For me some ideas to analyze the data:

Segmentation of the consumption daily pattern
Disaggregation of the electricity load curve
Cross the consumption result and the acorn information
Forecast the electricity consumption of a household, I wrote an article on this subject
What if I add electrical heating system ? an EV battery system ?
Forecast at a global scale (London consumption)


在本数据集中，您可以找到伦敦数据存储的重构版数据，其中包含 2011 年 11 月至 2014 年 2 月期间参与英国电力网络公司领导的低碳伦敦项目的 5567 户伦敦家庭的能源消耗读数样本。来自智能电表的数据似乎只与电力消耗相关联。

该数据集中有 19 个文件：

informations_households.csv：该文件包含面板中住户的所有信息（他们的橡子组、他们的电价），以及他们的数据存储在哪个 block.csv.gz 文件中。

halfhourly_dataset.zip： 包含智能电表半小时测量数据块文件的压缩文件

daily_dataset.zip： Zip 文件，包含每日信息的块文件，如测量次数、最小值、最大值、平均值、中位数、总和和 std.

acorn_details.csv：有关 acorn 小组及其小组成员概况的详细信息，来自此 xlsx 电子表格。前三列是所研究的属性，ACORN-X 是该属性的指数。在全国范围内，指数为 100，如果某一列的指数值为 150，则意味着 ACORN 群体中具有该属性的人数是全国范围内的 1.5 倍。您可以在 CACI 网站上找到相关解释

weather_daily_darksky.csv : 包含来自 darksky api 的每日数据。有关参数的更多详情，请参阅 api 文档

weather_hourly_darksky.csv : 包含来自 darksky api 的每小时数据。有关参数的更多详情，请参阅 api 文档。

灵感
我有一些分析数据的想法：

细分每日消费模式
分解电力负荷曲线
将用电结果与橡树果信息进行交叉分析
预测家庭用电量，我曾就此写过一篇文章
如果增加电加热系统和电动汽车电池系统会怎样？
全球范围的预测（伦敦的用电量）

This research aims to analyze and predict household energy consumption patterns in urban areas using a comprehensive dataset of smart meter readings from London.  The study will use Python as the primary tool for data analysis and model development. Key research components include:

1. Analyzing daily and hourly energy consumption patterns: Investigating energy usage trends across different households to identify common patterns and anomalies in daily or hourly energy consumption.

2. Neural Network-based prediction of household energy use: Developing a neural network model to predict household energy consumption. This model will integrate historical consumption data, weather conditions, and demographic information, aiming to assist in urban electricity grid management and planning.

3. Impact of weather conditions on energy consumption: Examining how different weather conditions influence energy usage patterns, utilizing detailed weather data collected through the Dark Sky API for the London area.

The aim of the study is to provide valuable insights for urban planners, energy providers and policymakers to enable more efficient energy management and planning in urban environments.


本研究旨在利用伦敦智能电表读数的综合数据集，分析和预测城市地区的家庭能源消耗模式。 研究将使用 Python 作为数据分析和模型开发的主要工具。主要研究内容包括

1. 分析每日和每小时的能源消耗模式： 调查不同家庭的能源使用趋势，找出每日或每小时能源消耗的共同模式和异常现象。

2. 基于神经网络的家庭能源使用预测： 开发一个神经网络模型来预测家庭能源消耗。该模型将整合历史能耗数据、天气条件和人口信息，旨在协助城市电网管理和规划。

3. 天气条件对能源消耗的影响： 利用通过黑暗天空应用程序接口（Dark Sky API）收集的伦敦地区详细天气数据，研究不同天气条件如何影响能源使用模式。

该研究旨在为城市规划者、能源供应商和政策制定者提供有价值的见解，以便在城市环境中实现更高效的能源管理和规划。

In [13]:
import pandas as pd

In [14]:
# informations_households.csv：该文件包含面板中住户的所有信息（他们的橡子组、他们的电价），以及他们的数据存储在哪个 block.csv.gz 文件中。        
informations_households = pd.read_csv('archive/informations_households.csv')
informations_households

          LCLid stdorToU    Acorn Acorn_grouped       file
0     MAC005492      ToU   ACORN-        ACORN-    block_0
1     MAC001074      ToU   ACORN-        ACORN-    block_0
2     MAC000002      Std  ACORN-A      Affluent    block_0
3     MAC003613      Std  ACORN-A      Affluent    block_0
4     MAC003597      Std  ACORN-A      Affluent    block_0
...         ...      ...      ...           ...        ...
5561  MAC002056      Std  ACORN-U       ACORN-U  block_111
5562  MAC004587      Std  ACORN-U       ACORN-U  block_111
5563  MAC004828      Std  ACORN-U       ACORN-U  block_111
5564  MAC001704      ToU  ACORN-U       ACORN-U  block_111
5565  MAC002774      ToU  ACORN-U       ACORN-U  block_111

[5566 rows x 5 columns]

在统计数据表里，"Std"和"ToU"分别代表标准（Standard）和使用时间（Time of Use）电价。使用时间电价（TOU）是一种灵活的电价制度，旨在鼓励消费者在需求和能源成本较低的非高峰时段使用电力，以此帮助减少高峰时段的能源需求，促进电网的平衡，并有助于降低用户的电费支出

In [32]:
informations_households.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5566 entries, 0 to 5565
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LCLid          5566 non-null   object
 1   stdorToU       5566 non-null   object
 2   Acorn          5566 non-null   object
 3   Acorn_grouped  5566 non-null   object
 4   file           5566 non-null   object
dtypes: object(5)
memory usage: 217.5+ KB

In [25]:
unique_Acorn = informations_households['Acorn'].unique()
print(unique_Acorn)
unique_Acorn

['ACORN-' 'ACORN-A' 'ACORN-B' 'ACORN-C' 'ACORN-D' 'ACORN-E' 'ACORN-F'
 'ACORN-G' 'ACORN-H' 'ACORN-I' 'ACORN-J' 'ACORN-K' 'ACORN-L' 'ACORN-M'
 'ACORN-N' 'ACORN-O' 'ACORN-P' 'ACORN-Q' 'ACORN-U']

array(['ACORN-', 'ACORN-A', 'ACORN-B', 'ACORN-C', 'ACORN-D', 'ACORN-E',
       'ACORN-F', 'ACORN-G', 'ACORN-H', 'ACORN-I', 'ACORN-J', 'ACORN-K',
       'ACORN-L', 'ACORN-M', 'ACORN-N', 'ACORN-O', 'ACORN-P', 'ACORN-Q',
       'ACORN-U'], dtype=object)

Acorn_grouped:['ACORN-'缺失值 'Affluent'富裕的 'Comfortable'舒适的 'Adversity'困难的 'ACORN-U'无法分类或未知数据，可能因为数据缺失或不适用于任何已定义的类别]

In [26]:
unique_Acorn_grouped = informations_households['Acorn_grouped'].unique()
print(unique_Acorn_grouped)
unique_Acorn_grouped

['ACORN-' 'Affluent' 'Comfortable' 'Adversity' 'ACORN-U']

array(['ACORN-', 'Affluent', 'Comfortable', 'Adversity', 'ACORN-U'],
      dtype=object)

In [15]:
# daily_dataset.zip: Zip 文件，包含每日信息的块文件，如测量次数、最小值、最大值、平均值、中位数、总和和 std。
# 一个示例文件 block_0.csv
daily_block_0 = pd.read_csv('archive/daily_dataset/daily_dataset/block_0.csv')
daily_block_0

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
0,MAC000002,2012-10-12,0.1385,0.154304,0.886,46,0.196034,7.098,0.000
1,MAC000002,2012-10-13,0.1800,0.230979,0.933,48,0.192329,11.087,0.076
2,MAC000002,2012-10-14,0.1580,0.275479,1.085,48,0.274647,13.223,0.070
3,MAC000002,2012-10-15,0.1310,0.213688,1.164,48,0.224483,10.257,0.070
4,MAC000002,2012-10-16,0.1450,0.203521,0.991,48,0.184115,9.769,0.087
...,...,...,...,...,...,...,...,...,...
25569,MAC005492,2014-02-24,0.1690,0.175042,0.378,48,0.073174,8.402,0.079
25570,MAC005492,2014-02-25,0.1550,0.160792,0.545,48,0.082118,7.718,0.079
25571,MAC005492,2014-02-26,0.1490,0.178542,0.687,48,0.120820,8.570,0.079
25572,MAC005492,2014-02-27,0.1140,0.146167,0.478,48,0.082616,7.016,0.079
25573,MAC005492,2014-02-28,0.0880,0.088000,0.088,1,NaN,0.088,0.088

In [36]:
daily_block_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25574 entries, 0 to 25573
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LCLid          25574 non-null  object
 1   day            25574 non-null  object
 2   energy_median  25574 non-null  float64
 3   energy_mean    25574 non-null  float64
 4   energy_max     25574 non-null  float64
 5   energy_count   25574 non-null  int64
 6   energy_std     25496 non-null  float64
 7   energy_sum     25574 non-null  float64
 8   energy_min     25574 non-null  float64
dtypes: float64(6), int64(1), object(2)
memory usage: 1.8+ MB

In [39]:
# halfhourly_dataset.zip: 包含智能电表半小时测量数据块文件的压缩文件
# 一个示例文件 block_0.csv
halfhourly_block_0 = pd.read_csv('archive/halfhourly_dataset/halfhourly_dataset/block_0.csv')
halfhourly_block_0

             LCLid                         tstp energy(kWh/hh)
0        MAC000002  2012-10-12 00:30:00.0000000             0
1        MAC000002  2012-10-12 01:00:00.0000000             0
2        MAC000002  2012-10-12 01:30:00.0000000             0
3        MAC000002  2012-10-12 02:00:00.0000000             0
4        MAC000002  2012-10-12 02:30:00.0000000             0
...            ...                          ...            ...
1222665  MAC005492  2014-02-27 22:00:00.0000000         0.182
1222666  MAC005492  2014-02-27 22:30:00.0000000         0.122
1222667  MAC005492  2014-02-27 23:00:00.0000000          0.14
1222668  MAC005492  2014-02-27 23:30:00.0000000         0.192
1222669  MAC005492  2014-02-28 00:00:00.0000000         0.088

[1222670 rows x 3 columns]

In [40]:
halfhourly_block_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1222670 entries, 0 to 1222669
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   LCLid           1222670 non-null  object
 1   tstp            1222670 non-null  object
 2   energy(kWh/hh)  1222670 non-null  object
dtypes: object(3)
memory usage: 28.0+ MB

In [23]:
daily_dataset = pd.read_csv('archive/daily_dataset.csv')
daily_dataset

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
0,MAC000131,2011-12-15,0.4850,0.432045,0.868,22,0.239146,9.505,0.072
1,MAC000131,2011-12-16,0.1415,0.296167,1.116,48,0.281471,14.216,0.031
2,MAC000131,2011-12-17,0.1015,0.189812,0.685,48,0.188405,9.111,0.064
3,MAC000131,2011-12-18,0.1140,0.218979,0.676,48,0.202919,10.511,0.065
4,MAC000131,2011-12-19,0.1910,0.325979,0.788,48,0.259205,15.647,0.066
...,...,...,...,...,...,...,...,...,...
3510428,MAC004977,2014-02-24,0.0950,0.118458,0.580,48,0.093814,5.686,0.052
3510429,MAC004977,2014-02-25,0.0675,0.084208,0.176,48,0.037107,4.042,0.046
3510430,MAC004977,2014-02-26,0.1080,0.120500,0.282,48,0.069332,5.784,0.046
3510431,MAC004977,2014-02-27,0.0720,0.114062,0.431,48,0.094482,5.475,0.047
3510432,MAC004977,2014-02-28,0.0970,0.097000,0.097,1,NaN,0.097,0.097

In [34]:
daily_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3510433 entries, 0 to 3510432
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   LCLid          object
 1   day            object
 2   energy_median  float64
 3   energy_mean    float64
 4   energy_max     float64
 5   energy_count   int64
 6   energy_std     float64
 7   energy_sum     float64
 8   energy_min     float64
dtypes: float64(6), int64(1), object(2)
memory usage: 241.0+ MB

In [41]:
# ？
# 一个示例文件 block_0.csv
hhblock_blokc_0 = pd.read_csv('archive/hhblock_dataset/hhblock_dataset/block_0.csv')
block_0

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25281,MAC005492,2014-02-23,0.165,0.206,0.149,0.101,0.115,0.120,0.102,0.105,...,0.296,0.750,0.315,0.326,0.293,0.287,0.213,0.287,0.245,0.222
25282,MAC005492,2014-02-24,0.219,0.236,0.288,0.219,0.165,0.086,0.111,0.095,...,0.303,0.378,0.253,0.193,0.212,0.193,0.192,0.297,0.168,0.170
25283,MAC005492,2014-02-25,0.194,0.185,0.150,0.095,0.081,0.082,0.081,0.112,...,0.545,0.233,0.245,0.194,0.215,0.201,0.241,0.162,0.157,0.167
25284,MAC005492,2014-02-26,0.205,0.183,0.186,0.165,0.194,0.114,0.080,0.090,...,0.298,0.224,0.239,0.242,0.237,0.246,0.333,0.202,0.232,0.203
25285,MAC005492,2014-02-27,0.167,0.112,0.120,0.083,0.083,0.112,0.081,0.082,...,0.325,0.258,0.259,0.243,0.222,0.250,0.182,0.122,0.140,0.192

In [42]:
block_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25286 entries, 0 to 25285
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LCLid   25286 non-null  object
 1   day     25286 non-null  object
 2   hh_0    25286 non-null  float64
 3   hh_1    25286 non-null  float64
 4   hh_2    25286 non-null  float64
 5   hh_3    25286 non-null  float64
 6   hh_4    25286 non-null  float64
 7   hh_5    25286 non-null  float64
 8   hh_6    25286 non-null  float64
 9   hh_7    25286 non-null  float64
 10  hh_8    25286 non-null  float64
 11  hh_9    25286 non-null  float64
 12  hh_10   25286 non-null  float64
 13  hh_11   25286 non-null  float64
 14  hh_12   25286 non-null  float64
 15  hh_13   25286 non-null  float64
 16  hh_14   25286 non-null  float64
 17  hh_15   25286 non-null  float64
 18  hh_16   25286 non-null  float64
 19  hh_17   25286 non-null  float64
 20  hh_18   25286 non-null  float64
 21  hh_19   25286 non-null  float64
 22  hh_20   25286 non-null  float64
 23  hh_21   25286 non-null  float64
 24  hh_22   25286 non-null  float64
 25  hh_23   25286 non-null  float64
 26  hh_24   25286 non-null  float64
 27  hh_25   25285 non-null  float64
 28  hh_26   25286 non-null  float64
 29  hh_27   25286 non-null  float64
 30  hh_28   25286 non-null  float64
 31  hh_29   25286 non-null  float64
 32  hh_30   25237 non-null  float64
 33  hh_31   25286 non-null  float64
 34  hh_32   25286 non-null  float64
 35  hh_33   25286 non-null  float64
 36  hh_34   25286 non-null  float64
 37  hh_35   25286 non-null  float64
 38  hh_36   25286 non-null  float64
 39  hh_37   25286 non-null  float64
 40  hh_38   25286 non-null  float64
 41  hh_39   25286 non-null  float64
 42  hh_40   25286 non-null  float64
 43  hh_41   25286 non-null  float64
 44  hh_42   25286 non-null  float64
 45  hh_43   25286 non-null  float64
 46  hh_44   25286 non-null  float64
 47  hh_45   25286 non-null  float64
 48  hh_46   25286 non-null  float64
 49  hh_47   25286 non-null  float64
dtypes: float64(48), object(2)
memory usage: 9.6+ MB

In [18]:
# acorn_details.csv：有关 acorn 小组及其小组成员概况的详细信息，来自此 xlsx 电子表格。前三列是所研究的属性，ACORN-X 是该属性的指数。在全国范围内，指数为 100，如果某一列的指数值为 150，则意味着 ACORN 群体中具有该属性的人数是全国范围内的 1.5 倍。您可以在 CACI 网站上找到相关解释
acorn_details = pd.read_csv('archive/acorn_details.csv', encoding='windows-1252')
acorn_details

,MAIN CATEGORIES,CATEGORIES,REFERENCE,ACORN-A,ACORN-B,ACORN-C,ACORN-D,ACORN-E,ACORN-F,ACORN-G,ACORN-H,ACORN-I,ACORN-J,ACORN-K,ACORN-L,ACORN-M,ACORN-N,ACORN-O,ACORN-P,ACORN-Q
0,POPULATION,Age,Age 0-4,77.0,83.0,72.0,100.0,120.0,77.0,97.0,97.0,63.0,119.0,67.0,114.0,113.0,89.0,123.0,138.0,133.0
1,POPULATION,Age,Age 5-17,117.0,109.0,87.0,69.0,94.0,95.0,102.0,106.0,67.0,95.0,64.0,108.0,116.0,86.0,89.0,136.0,106.0
2,POPULATION,Age,Age 18-24,64.0,73.0,67.0,107.0,100.0,71.0,83.0,89.0,62.0,104.0,459.0,97.0,96.0,86.0,117.0,109.0,110.0
3,POPULATION,Age,Age 25-34,52.0,63.0,62.0,197.0,151.0,66.0,90.0,88.0,63.0,132.0,145.0,109.0,96.0,90.0,140.0,120.0,120.0
4,POPULATION,Age,Age 35-49,102.0,105.0,91.0,124.0,118.0,93.0,102.0,103.0,76.0,111.0,67.0,99.0,98.0,90.0,102.0,103.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,LEISURE TIME,Holiday Destination/Type,Asia,171.0,137.0,94.0,220.0,196.0,69.0,122.0,95.0,72.0,97.0,124.0,73.0,57.0,49.0,96.0,113.0,63.0
822,LEISURE TIME,Holiday Destination/Type,Activity / Outdoor Sports,298.0,278.0,138.0,119.0,93.0,96.0,113.0,96.0,84.0,96.0,56.0,48.0,48.0,46.0,23.0,23.0,23.0
823,LEISURE TIME,Holiday Destination/Type,Cruise,272.0,295.0,272.0,44.0,44.0,70.0,70.0,70.0,70.0,70.0,28.0,28.0,28.0,28.0,49.0,49.0,49.0
824,LEISURE TIME,Holiday Destination/Type,Package,196.0,186.0,166.0,49.0,49.0,101.0,101.0,121.0,106.0,101.0,48.0,75.0,75.0,75.0,54.0,54.0,54.0
825,LEISURE TIME,Holiday Destination/Type,Self-catering,308.0,181.0,181.0,55.0,55.0,127.0,147.0,124.0,113.0,166.0,44.0,44.0,44.0,33.0,32.0,35.0,35.0

In [33]:
acorn_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 826 entries, 0 to 825
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MAIN CATEGORIES  826 non-null    object
 1   CATEGORIES       826 non-null    object
 2   REFERENCE        825 non-null    object
 3   ACORN-A          826 non-null    float64
 4   ACORN-B          826 non-null    float64
 5   ACORN-C          826 non-null    float64
 6   ACORN-D          826 non-null    float64
 7   ACORN-E          826 non-null    float64
 8   ACORN-F          826 non-null    float64
 9   ACORN-G          826 non-null    float64
 10  ACORN-H          826 non-null    float64
 11  ACORN-I          826 non-null    float64
 12  ACORN-J          826 non-null    float64
 13  ACORN-K          826 non-null    float64
 14  ACORN-L          826 non-null    float64
 15  ACORN-M          826 non-null    float64
 16  ACORN-N          826 non-null    float64
 17  ACORN-O          826 non-null    float64
 18  ACORN-P          826 non-null    float64
 19  ACORN-Q          826 non-null    float64
dtypes: float64(17), object(3)
memory usage: 129.2+ KB

In [31]:
unique_main_categories = acorn_details['MAIN CATEGORIES'].unique()
print('unique_main_categories:', unique_main_categories)

unique_categories = acorn_details['CATEGORIES'].unique()
print('unique_categories:', unique_categories)

unique_Reference = acorn_details['REFERENCE'].unique()
print('unique_Reference:', unique_Reference)

unique_main_categories: ['POPULATION' 'HOUSING' 'FAMILY' 'ECONOMY' 'EDUCATION' 'HEALTH'
 'TRANSPORT' 'MARKETING CHANNELS' 'FINANCE' 'DIGITAL' 'SHOPPING' 'CONTACT'
 'ENVIRONMENT' 'COMMUNITY SAFETY' 'LEISURE TIME']
unique_categories: ['Age' 'Geography' 'Ethnicity' 'Country of Birth' 'Religion' 'House Type'
 'House Tenure' 'House Size' 'House Value' 'Moving House' 'Structure'
 'Children in household' 'Household Size' 'Economic Activity'
 'NS Socio-Economic Classifications' 'Social Grade' 'Occupation'
 'Highest Level of Qualifications (Adults)'
 'England: Pupils at the end of KS1' 'England: Pupils at the end of KS2'
 'England: Pupils at the end of KS4' 'Scotland: Pupils in the S4 cohort'
 'Scotland: Pupils in the S5 cohort' 'Behaviours & Lifestyle'
 'Travel To Work' 'Public Transport Accessibility Level' 'Car Ownership'
 'Main Car Class' 'Channels Received' 'Future Responses'
 'Household Annual Income' 'Financial Attitudes' 'Financial Situation'
 'Benefits' 'Credit Cards' 'Savings and Investments' 'Loans'
 'Insurance and Pensions' 'Financial Channel: Arrange Current Account'
 'Financial Channel: Arrange commoditised financial product'
 'Financial Channel: Arrange considered financial product'
 'Financial Channel: Manage Current Account'
 'Financial Channel: Manage Savings Account'
 'Expenditure per person per week' 'Internet Access: Frequency'
 'Internet Access: Usage in Last Week' 'Digital Attitudes'
 'Technology at Home' 'TV on Demand' 'Mobile phone' 'Smartphone Brand'
 'Tablet Devices' 'Social Media Activity (at least weekly)'
 'Social Media Brands (used at least weekly)'
 'Number of apps on mobile phone (free or paid)'
 'Types of internet usage : Laptop or PC'
 'Types of internet usage : Mobile Phone'
 'Types of internet usage : Tablet / iPad'
 'Regularly research on the internet' 'Purchased on the internet'
 'Sites regularly visited' 'Preferred Supermarket' 'Food Shopping'
 'Clothing & Footwear Stores' 'Furniture & Fittings Stores'
 'Electrical Stores' 'High Street Retailers' 'Attitudes'
 'Preferred Channel' 'Environmental Groups' 'Action' 'Attitude'
 'Crime Survey for England' 'Daily Newspapers' 'Magazines Read'
 'Charities' 'Books Read' 'Interests & Hobbies'
 'Visit Pubs for a Drink - Day' 'Visit Pubs for a Drink - Evening'
 'Visit Pubs for a Meal - Day' 'Visit Pubs for a Meal - Evening'
 'Restaurants - Most Often' 'Holiday Destination/Type']
unique_Reference: ['Age 0-4' 'Age 5-17' 'Age 18-24' 'Age 25-34' 'Age 35-49' 'Age 50-64'
 'Aged 65-74' 'Aged 75 plus' 'England' 'Northern Ireland' 'Scotland'
 'Wales' 'White' 'Mixed' 'Asian' 'Black' 'Other ethnicity' 'UK / ROI'
 'EU: Member countries in March 2001'
 'EU: Accession countries April 2001 to March 2011' 'Rest of Europe'
 'Africa' 'Middle East & Asia' 'North America' 'Central America'
 'South America' 'Caribbean' 'Antarctica & Oceania' 'Christian' 'Jewish'
 'Buddhist' 'Muslim' 'Hindu' 'Sikh' 'Other religion' 'Bungalow'
 'Detached house' 'Flat or maisonette' 'Semi-detached house'
 'Terraced house' 'Owner occupied' 'Owned outright' 'Mortgaged'
 'Privately rented' 'Social renting' 'Shared/Equity Ownership'
 'Number of Beds : 1' 'Number of Beds : 2' 'Number of Beds : 3'
 'Number of Beds : 4' 'Number of Beds : 5 plus' 'House Value up to 100k'
 'House Value 100k-150k' 'House Value 150k-250k' 'House Value 250k-500k'
 'House Value 500k-750k' 'House Value 750k-1m' 'House Value 1m+'
 'Individual likely to move within 12 months' 'Couple family no children'
 'Couple family with dependent children'
 'Lone parent family with dependent children' 'All pensioner households'
 'All student households' 'One person household (non-pensioner)'
 'Other household structure' 'Children at home : 0' 'Children at home : 1'
 'Children at home : 2' 'Children at home : 3+'
 'Household size : 1 person' 'Household size : 2 persons'
 'Household size : 3-4 persons' 'Household size : 5+ persons'
 'Employee Full-Time' 'Employee Part-Time' 'Self-employed' 'Retired'
 'Unemployed and seeking work' 'Student' 'Looking after home or family'
 'Other economic activity'
 'Higher managerial, administrative and professional occupations'
 'Lower managerial, administrative and professional occupations'
 'Intermediate occupations' 'Small employers and own account workers'
 'Lower supervisory and technical occupations' 'Semi-routine occupations'
 'Routine occupations' 'Never worked and long-term unemployed'
 'Full time students and SEC Unclassified' 'A' 'B' 'C1' 'C2' 'D' 'E'
 'Director / Managerial' 'Professional' 'Housewife' 'Office Worker'
 'Public Sector' 'Self Employed' 'Shop Worker' 'Skilled / Manual Worker'
 'Unemployed' 'No formal qualifications'
 'GCSE / O levels / CSE / School Certificate'
 'ONC / BTEC / apprenticeship' 'A-levels/ AS levels or Highers'
 'Higher education below degree level' 'Degree or higher degree'
 'Achieving expected level in reading'
 'Achieving expected level in writing' 'Achieving expected level in maths'
 'Achieving expected level in science'
 'Achieving expected level in reading, writing and maths'
 'Achieving 5+ A*-C at GCSE or equivalent'
 'Achieving 5+ A*-C (including English and Maths) at GCSE or equivalent'
 'Attained 5 awards at SCQF level 5 and above'
 'Attained 3 awards at SCQF level 6 and above'
 'Attained 5 awards at SCQF level 6 and above' 'Current cigarette smoker'
 'Takes regular exercise'
 'I like to pursue a life of challenge, novelty and change'
 'I am perfectly happy with my standard of living'
 'I worry a lot about myself' 'Eats fruit 3 or less days per week'
 'Eats vegetables 3 or less days per week' 'Work mainly at or from home'
 'Train / Tube / Tram' 'Car, van or motorbike (driver or passenger)'
 'Bus, Minibus, Coach' 'Taxi' 'Bicycle' 'On foot'
 'Other mode of travel to work' '1a - Extremely Poor Accessibility' '1b'
 '2' '3' '4' '5' '6a' '6b - Excellent Access' 'Number of Cars 0'
 'Number of Cars 1' 'Number of Cars 2' 'Number of Cars 3+'
 'Mini or Supermini' 'Small Family' 'Large Family' 'Luxury or Executive'
 'Sports or 4x4 or MPV' 'Leaflets - Door or Newspaper'
 "Mail - Addressed to 'The Householder' or 'The Occupier'"
 'Mail - Addressed to you by name' 'Newspaper / Magazine Adverts'
 'TV/Radio'
 'Leaflets/Samples handed out in the street or picked up in shop'
 'Posters' 'Email' 'Internet Advertising' 'Messages on mobile phone'
 'Telemarketing' 'Cinema Advertising'
 "Email from companies you don't know" 'Email from companies you do know'
 'Offers/Promotions on product packaging' '£0-£20,000' '£20,000-£40,000'
 '£40,000-£60,000' '£60,000-£80,000' '£80,000-£100,000' '£100,000+'
 'Average Household Income' "I don't like the idea of being in debt"
 'I am very good at managing money'
 'It is important to be well insured for everything'
 'Financial security after retirement is your own responsibility'
 'Uses contactless payments on debit card' 'Saving' 'Not saving'
 'Saving a lot' 'Saving a little' 'Just managing to make ends meet'
 'Drawing on savings or running into debt' "Job Seeker's Allowance"
 'Disability Living Allowance' 'Income Support' 'Has credit card'
 'Has 2+ credit cards' 'Spent £500+ in last month on a credit card'
 'Uses credit card 6+ times per month'
 'Usually makes minimum payment on card'
 'Always pays credit card balance in full' 'Has savings account'
 'Has instant access account' 'Has Cash ISA' 'Has Stocks and Shares ISA'
 'Has Unit Trusts' 'Has stocks and shares' 'Has investment bonds'
 'Has a National Savings product' 'Has Investments'
 'Value of investments £25,000+' 'Savings value £1 - £500'
 'Savings value £500 - £2,500' 'Savings value £2,500 - £10,000'
 'Savings value £10,000+' 'Has loan' 'Has unsecured loan' 'Has 2+ loans'
 'Unsecured debt greater than £15,000' 'Has Private Health Care'
 'Has Company Health Care' 'Has Life Assurance'
 'Has life protection policy'
 'Has pension scheme organised through company'
 'Has pension scheme organised personally'
 'Plans to use other investments for retirement'
 'In branch or other face to face' 'Online' 'By phone' 'By post'
 'Used price comparison site' 'Used IFA' 'In branch' 'Online mobile'
 'Online at home or work' 'Total Expenditure'
 'Food and non-alcoholic beverages' 'Alcoholic beverages and tobacco'
 'Clothing and footwear'
 'Housing, water, electricity, gas and other fuels'
 'Furnishings, household equipment and routine maintenance' 'Health'
 'Transport' 'Communication' 'Recreation and Culture' 'Education'
 'Restaurants and hotels' 'Miscellaneous goods and services'
 'Total Online Expenditure' 'Weekly' 'Monthly' 'Less than once a month'
 'Never used the internet' 'Not at all' 'Less than 2 hours' '3-7 hours'
 '8-19 hours' '20 hours or more'
 'I worry that any personal information entered online will not remain secure'
 "I couldn't live without the internet on my mobile"
 "Computers confuse me, I'll never get used to them"
 'I love to buy new gadgets and appliances'
 'I wait until technology becomes cheaper before considering a purchase'
 'Shopping online makes my life easier' 'Portable Media Player'
 'Videogame console' 'Has a smartwatch, fitness band or payment band'
 'Watch on a PC' 'Watch on a TV set' 'Watch on a Mobile phone/Device'
 'Has Mobile Phone with access to Internet' 'BlackBerry' 'iPhone' 'HTC'
 'LG' 'Motorola' 'Nokia' 'Samsung' 'Sony Ericsson'
 'Has Tablet (e.g. iPad, Samsung Galaxy Tab, Sony Xperia)'
 'Visit the profile/fan page of a product/brand or celebrity'
 'Interact with a brand (e.g. like the content that brand posted, comment on a brand page, tweet a brand)'
 'Look for business contacts' 'Look for a job' 'Play games'
 'Share/upload content/links you have found (e.g. photos, videos)'
 'Make comments on your friends’ status, photos etc'
 'Look at content/updates your friends have posted (e.g. photos, videos, status updates)'
 'Update your profile (e.g. pictures, hobbies)'
 'Update your status/tell people what you are up to/tell people what’s happening'
 'Access services/other social networks through apps on Facebook (e.g. Spotify, Pinterest, Instagram)'
 'Watch video content' 'Direct messaging' 'Take and upload a video/photo'
 'Trying to meet new people' 'Browsing to see what my friends are up to'
 'Foursquare' 'YouTube' 'LinkedIn' 'Twitter' 'Google +' 'Facebook'
 'Flickr' 'Pinterest' 'Instagram' 'Tumblr' 'Vine' 'Snapchat' 'WhatsApp'
 'Viber' 'Tinder' 'Reddit' 'Shazam' 'Blogs/online forums' nan '1-10.'
 '11-20.' '21-30' '31-50' '51+' 'Enter competitions'
 'Access content via an electronic bar code (QR scanner) (e.g. eBay scanner)'
 'Use GPS services (e.g. Maps)' 'Use Skype' 'Listen to Music'
 'Vote on television shows (e.g. X Factor, Strictly Come Dancing)'
 'Download content/information from an advertising poster'
 'Send and receive personal emails' 'Listen to the radio'
 'Send pictures/videos to others' 'Take pictures/video clips'
 'Receive/Redeem coupons and vouchers'
 'Source info on products/services via Internet'
 'Book tickets via the Internet' 'Download music via the Internet'
 'Instant messaging' 'Locate places/shops/businesses via the Internet'
 'Watch TV/films/video clips via the Internet'
 'Manage personal finances (banking) via the Internet'
 'Update my location (e.g. places/via Foursquare)'
 'Use augmented reality apps (e.g. blippar)'
 'Read customer ratings/reviews' 'Post ratings and reviews'
 'Take part in discussion groups/online forums'
 'Check stocks/shares/investments' 'Donate to charity'
 'Commenting on someone else’s blog, or their content/opinions'
 'Read someone else’s blog' 'Write your own blog/homepage' 'Online dating'
 'Access news via news site (other than online newspapers)'
 'Download a Podcast' 'Gambling/Betting' 'Online auctions (e.g. ebay)'
 'School/College/University work'
 'Watch online videos made by other users (e.g. YouTube)'
 'Social networking (e.g. Facebook, Twitter)' 'Read newspapers online'
 'Read magazines online' 'Play games with my children'
 'Managing a website/page you have published'
 'Upload content (video, articles, music, etc) that you have created'
 'Stream/Watch live events (e.g. Music, Sport etc.)'
 'Make an online purchase' 'Pay for things with my mobile phone'
 'Computer/Video games' 'Loans' 'Savings/Investments' 'Credit Cards'
 'Current Accounts' 'Local Government Services'
 'Household utilities (e.g. Gas, Electricity)' 'Musical equipment'
 'Furniture' 'Beer/Wine/Spirits' 'Travel tickets (non airline)' 'Toys'
 'Tickets for events/cinema/theatre' 'Sports equipment' 'Property'
 'Mobile phones/mobile accessories' 'Mortgages' 'Home Insurance'
 'Car Insurance' 'Other Insurance (e.g. Life, Travel)' 'Eating out'
 'Days out' 'Gardening equipment/flowers/plants'
 'Household electrical products' 'Videos/DVDs/MP4'
 'Computer Software/programmes/hardware' 'Music (e.g. CDs, MP3s)'
 'Vehicles' 'Books' 'Consumer electronics (e.g. TVs, Stereos)'
 'Hotel reservations' 'Airline tickets' 'Sports and Leisurewear/trainers'
 'Personal electronic products (e.g. electric razors)'
 'Domestic appliances (e.g. fridge, washing machine)'
 'Personal grooming products (e.g. skin care, fragrances, etc.)'
 'Holidays' 'Clothes/Accessories' 'Groceries' 'None of these'
 'Personal grooming products ( e.g. skin care, fragrances, etc.)'
 '888.com' 'Air B’n’B' 'Amazon.co.uk' 'AOL UK' 'Apple' 'Argos' 'Asos.com'
 'Audible (Amazon eBooks)' 'Auto Trader' 'bbc.co.uk' 'Bet365.com' 'Bing'
 'Blinkbox' 'Boots.com' 'Buzzfeed' 'Carphone Warehouse'
 'comparethemarket.com' 'Confused.com' 'DigitalSpy' 'Direct.gov.uk'
 'Dropbox' 'Ebay' 'EE.co.uk' 'eHow.com' 'Expedia.co.uk' 'Freecycle'
 'Game.co.uk' 'Gocompare.com' 'Google.co.uk' 'Groupon' 'Gumtree.com'
 'HotUKDeals' 'Huffington Post' 'Hungry House'
 'Internet Movie Database (IMDB)' 'iTunes' 'johnlewis.com' 'JustEat'
 'Kelkoo.co.uk' 'Last.fm' 'Lastminute.com' 'Live.com' 'LOVEFiLM'
 'Marks and Spencer' 'Match.com' 'meccabingo.com' 'Microsoft'
 'Moneysavingexpert.com' 'Moneysupermarket.com' 'Mumsnet' 'Myvouchercodes'
 'National Lottery' 'National Rail' 'Net doctor' 'Net-a-Porter'
 'Netmums.com' 'NHS Direct' 'Notonthehighstreet.com'
 'Outlook.com (Previously Hotmail)' 'Play.com' 'Quidco' 'RAC.co.uk'
 'Reuters.com' 'rightmove.co.uk' 'Selfridges' 'Sky Sports' 'Sky.co.uk'
 'SoundCloud' 'Spotify' 'Stumble Upon' 'Tesco.net/Tesco.com'
 'tfl.gov.uk (Transport for London)' 'theaa.com' 'TheLadBible'
 'Ticketmaster' 'Timeout' 'Top Gear' 'Topshop' 'Tripadvisor' 'VEVO'
 'Wikipedia' 'Yahoo.co.uk' 'Yell.com' 'zoopla.co.uk' 'Asda' 'Co-op'
 'M & S' 'Morrisons' 'Sainsburys' 'Tesco' 'Waitrose' 'Fairtrade'
 'Premium Ranges' 'Budget Ranges' 'Healthy Option Ranges' 'Premium'
 'Mass Market' 'Value' 'Boots The Chemist' 'Costa' 'Debenhams' 'H&M'
 'John Lewis' 'Marks & Spencer' 'McDonalds' 'New Look' 'Next' 'Poundland'
 'Primark' 'Sports Direct'
 'I am prepared to pay more for products that make life easier'
 "It's worth paying extra for quality goods"
 'I buy goods produced in my own country whenever I can'
 'I tend to go for premium rather than standard goods/services'
 'I like to pay cash for everything I buy'
 'I decide what I want before I do the weekly shopping'
 'I prefer not to shop in major high street chains'
 'I look for the lowest possible prices when I go shopping'
 'Shopping for groceries is a bore'
 'I only shop at supermarkets that sell good quality fresh food'
 'I check a number of sources before making a significant purchase'
 'Phone or SMS' 'Mail' 'Visit' 'Member of Environmental Group'
 'Rarely Leave TV or PC on standby for long periods of time at home'
 'Rarely keep the tap running while brushing teeth'
 'Rarely leave the heating on when out for a few hours'
 'Decide not to buy something because it has too much packaging'
 'Take own shopping bag when shopping'
 'Re-use items like empty bottles, tubs, jars, envelopes or paper'
 'Rarely leave the mobile phone charger in the socket when not in use'
 'Recycle items rather than throwing them away'
 'Make an effort to cut down on the use of gas/electricity at home'
 'Make an effort to cut down on water usage at home'
 'There is too much concern with the environment: Agree'
 'Too lenient sentencing' 'Poverty' 'Lack of discipline from school'
 'Lack of discipline from parents' 'Drugs' 'Alcohol' 'Unemployment'
 'Breakdown of family' 'Too few police' 'Home being broken into'
 'Being mugged and robbed' 'Having my car stolen'
 'Things being stolen from my car'
 'Being physically attacked by strangers' 'Being raped'
 'Being attacked because of skin colour, ethnic origin or religion'
 'The police in this area can be relied on to be there when you need them'
 'The police in this area would treat you with respect if you had contact with them'
 'The police in this area treat everyone fairly regardless of who they are'
 'The police in this area understand the issues that affect this community'
 'The police in this area are dealing with the things that matter to this community'
 'Taking everything into account I have confidence in the police in this area'
 'Daily Express' 'Daily Star' 'The Sun' 'The Times' 'Daily Mail'
 'Daily Mirror' 'Daily Record' 'Daily Telegraph' 'The Guardian'
 'The Independent' 'Business/Educational/Science' 'Celebrity'
 'Food and Cooking' 'Home and Gardening' 'Computers and Electrical'
 'Men Style and Generic' 'Motor' 'Music and Film' 'Sport' 'Travel' 'TV'
 "Women's" "Women's Glossy" 'Animal Welfare' 'Childrens Welfare'
 'Disability' 'Disaster Relief' 'Elderly' 'Environment/Wildlife' 'Medical'
 'Overseas Development' 'Cancer' 'Homeless' 'Visual impairment'
 'Mental Health' 'Regularly donate to charity' 'History/Biography'
 'Health/Alternative Therapy' 'Science Fiction/Fantasy'
 'Mystery/Detective/Thrillers' 'Romance' 'Best Sellers' 'Angling'
 'Charity / Voluntary Work' 'Cinema' 'Cookery' 'DIY'
 'Antiques or Fine Art' 'Eating Out' 'Environment / Wildlife'
 'Exercise / Sports' 'Foreign Travel' 'Gambling' 'Gardening'
 'Playing Golf' 'Healthy Eating' 'Hiking / Walking' 'Organic Foods' 'Pets'
 'Reading Books' 'Records / Tapes / CDs' 'Vegetarian Products'
 'Football Supporter' 'UK / Ireland' 'Spain / Mediterranean'
 'Europe (other)' 'USA / Canada' 'Australia / New Zealand' 'Asia'
 'Activity / Outdoor Sports' 'Cruise' 'Package' 'Self-catering']

Main Categories (主要类别): 描述 ACORN 分组的主要类别，如人口、住房、经济等。
POPULATION (人口): 包含年龄、性别、人口密度等基本人口统计信息。
HOUSING (住房): 描述住宅类型、居住条件、房屋所有权等住房相关数据。
FAMILY (家庭): 涵盖家庭结构、家庭大小、婚姻状况等信息。
ECONOMY (经济): 包括就业率、行业分布、收入水平等经济活动和特征。
EDUCATION (教育): 教育水平、在校学生人数、教育机构分布等教育相关数据。
HEALTH (健康): 医疗设施可达性、健康状况指标、疾病发病率等健康信息。
TRANSPORT (交通): 交通方式、通勤时间、公共交通可用性等交通情况。
MARKETING CHANNELS (营销渠道): 消费者获取信息和购买产品的渠道，如社交媒体、传统媒体等。
FINANCE (财务): 描述信用状况、投资偏好、银行服务使用等财务行为。
DIGITAL (数字): 网络使用习惯、电子设备拥有率、数字技能等数字化生活方面的数据​​。
SHOPPING (购物): 购物行为、消费偏好、购买力等消费者购物相关信息。
CONTACT (联系): 社交互动、社区参与、通讯方式等社会联系方式。
ENVIRONMENT (环境): 环境质量、绿地覆盖率、污染水平等环境状况。
COMMUNITY SAFETY (社区安全): 犯罪率、公共安全感知、紧急服务可达性等社区安全信息。
LEISURE TIME (休闲时间): 休闲活动、娱乐偏好、休闲设施使用等闲暇时间如何度过的数据。

Categories (类别): 描述 ACORN 分组的具体类别，如年龄段、家庭类型、收入水平等。
Age, Geography, Ethnicity, Country of Birth, Religion 等列关注基本人口统计信息，如年龄、居住地理位置、种族背景、出生国家和宗教信仰，这些是了解一个人口集合基本属性的关键因素。

House Type, House Tenure, House Size, House Value 和 Moving House 则提供有关居住环境的详细信息，包括住房类型、拥有权情况、房屋大小、估值以及是否近期搬家等。

Economic Activity, NS Socio-Economic Classifications, Social Grade, Occupation 以及 Household Annual Income 等列涵盖经济活动和社会经济地位，聚焦于职业、收入水平以及社会等级划分。

Highest Level of Qualifications (Adults) 和关于英格兰与苏格兰学生学业成绩的列（如 England: Pupils at the end of KS1）提供教育水平和学业成就的数据。

Behaviours & Lifestyle 包括旅行、公共交通可及性、汽车拥有情况等生活方式和行为习惯的信息。

Financial Attitudes, Financial Situation, Benefits, Credit Cards, Savings and Investments, Loans 以及 Insurance and Pensions 等列关注个人或家庭的财务状况和态度，包括信用卡使用、储蓄投资情况、贷款以及保险和养老金情况。

Digital Attitudes, Technology at Home, Internet Access, Social Media Activity 等列探索数字技术使用情况和互联网行为，包括家庭中的技术设备、互联网接入频率以及社交媒体使用情况。

Food Shopping, Clothing & Footwear Stores, Furniture & Fittings Stores 等列则提供消费行为和购物偏好的洞察，涉及食品购物、衣物鞋类和家具家装的购买地点选择。

Environmental Groups, Action, Attitude 列提供有关环境观念和行动的信息，反映个人或社区对环保议题的态度和参与程度。

Crime Survey for England, Daily Newspapers, Magazines Read, Charities, Books Read, Interests & Hobbies 等列提供更为细致的生活方式、媒体消费习惯、兴趣爱好以及社会参与等信息

reference(参考）

人口统计特征
Age 0-4, Age 5-17, 等：特定年龄段的人口。
England, Northern Ireland, Scotland, Wales：居住地区域。
White, Mixed, Asian, Black, Other ethnicity：种族背景。
UK / ROI, EU: Member countries in March 2001, 等：出生地区域，包括英国、爱尔兰共和国、欧盟成员国等。
Christian, Jewish, Buddhist, Muslim, Hindu, Sikh, Other religion：宗教信仰。
居住环境
Bungalow, Detached house, Flat or maisonette, 等：住宅类型。
Owner occupied, Owned outright, Mortgaged, 等：住房拥有权情况。
Number of Beds : 1, Number of Beds : 2, 等：房屋床位数。
House Value up to 100k, House Value 100k-150k, 等：房屋价值。
家庭和社会经济地位
Couple family no children, Couple family with dependent children, 等：家庭类型。
Employee Full-Time, Employee Part-Time, Self-employed, 等：经济活动状况。
Higher managerial, Lower managerial, Intermediate occupations, 等：社会经济分类。
A, B, C1, C2, D, E：社会等级。
教育和技能
No formal qualifications, GCSE / O levels / CSE, 等：最高教育水平。
Achieving expected level in reading, writing, 等：在特定教育阶段达到的预期学习水平。
生活方式和消费行为
Current cigarette smoker, Takes regular exercise：生活习惯和行为。
Train / Tube / Tram, Car, van or motorbike, 等：上班通勤方式。
Number of Cars 0, Number of Cars 1, 等：汽车拥有数量。
Food Shopping, Clothing & Footwear Stores, 等：购物偏好。
金融和消费
Household Annual Income, Financial Attitudes, Financial Situation, 等：家庭年收入、金融态度和财务状况。
Savings and Investments, Loans, Insurance and Pensions：储蓄投资、贷款以及保险和养老金。
数字和技术
Internet Access: Frequency, Digital Attitudes, Technology at Home, 等：互联网使用频率、数字态度和家中技术设备。
Social Media Activity (at least weekly), Social Media Brands (used at least weekly), 等：社交媒体活动和常用平台。

In [19]:
# uk_bank_holidays.csv : 包含英国银行假日的数据
uk_bank_holidays = pd.read_csv('archive/uk_bank_holidays.csv')
uk_bank_holidays

   Bank holidays                                          Type
0     2012-12-26                                    Boxing Day
1     2012-12-25                                 Christmas Day
2     2012-08-27                           Summer bank holiday
3     2012-05-06  Queen?s Diamond Jubilee (extra bank holiday)
4     2012-04-06          Spring bank holiday (substitute day)
5     2012-07-05                        Early May bank holiday
6     2012-09-04                                 Easter Monday
7     2012-06-04                                   Good Friday
8     2012-02-01               New Year?s Day (substitute day)
9     2013-12-26                                    Boxing Day
10    2013-12-25                                 Christmas Day
11    2013-08-26                           Summer bank holiday
12    2013-05-27                           Spring bank holiday
13    2013-06-05                        Early May bank holiday
14    2013-01-04                                 Easter Monday
15    2013-03-29                                   Good Friday
16    2013-01-01                                New Year?s Day
17    2014-12-26                                    Boxing Day
18    2014-12-25                                 Christmas Day
19    2014-08-25                           Summer bank holiday
20    2014-05-26                           Spring bank holiday
21    2014-05-05                        Early May bank holiday
22    2014-04-21                                 Easter Monday
23    2014-04-18                                   Good Friday
24    2014-01-01                                New Year?s Day

In [35]:
uk_bank_holidays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bank holidays  25 non-null     object
 1   Type           25 non-null     object
dtypes: object(2)
memory usage: 528.0+ bytes

In [20]:
# weather_daily_darksky.csv : 包含来自 darksky api 的每日数据。有关参数的更多详情，请参阅 api 文档
weather_daily_darksky = pd.read_csv('archive/weather_daily_darksky.csv')
weather_daily_darksky

,temperatureMax,temperatureMaxTime,windBearing,icon,dewPoint,temperatureMinTime,cloudCover,windSpeed,pressure,apparentTemperatureMinTime,...,temperatureHigh,sunriseTime,temperatureHighTime,uvIndexTime,summary,temperatureLowTime,apparentTemperatureMin,apparentTemperatureMaxTime,apparentTemperatureLowTime,moonPhase
0,11.96,2011-11-11 23:00:00,123,fog,9.40,2011-11-11 07:00:00,0.79,3.88,1016.08,2011-11-11 07:00:00,...,10.87,2011-11-11 07:12:14,2011-11-11 19:00:00,2011-11-11 11:00:00,Foggy until afternoon.,2011-11-11 19:00:00,6.48,2011-11-11 23:00:00,2011-11-11 19:00:00,0.52
1,8.59,2011-12-11 14:00:00,198,partly-cloudy-day,4.49,2011-12-11 01:00:00,0.56,3.94,1007.71,2011-12-11 02:00:00,...,8.59,2011-12-11 07:57:02,2011-12-11 14:00:00,2011-12-11 12:00:00,Partly cloudy throughout the day.,2011-12-12 07:00:00,0.11,2011-12-11 20:00:00,2011-12-12 08:00:00,0.53
2,10.33,2011-12-27 02:00:00,225,partly-cloudy-day,5.47,2011-12-27 23:00:00,0.85,3.54,1032.76,2011-12-27 22:00:00,...,10.33,2011-12-27 08:07:06,2011-12-27 14:00:00,2011-12-27 00:00:00,Mostly cloudy throughout the day.,2011-12-27 23:00:00,5.59,2011-12-27 02:00:00,2011-12-28 00:00:00,0.10
3,8.07,2011-12-02 23:00:00,232,wind,3.69,2011-12-02 07:00:00,0.32,3.00,1012.12,2011-12-02 07:00:00,...,7.36,2011-12-02 07:46:09,2011-12-02 12:00:00,2011-12-02 10:00:00,Partly cloudy throughout the day and breezy ov...,2011-12-02 19:00:00,0.46,2011-12-02 12:00:00,2011-12-02 19:00:00,0.25
4,8.22,2011-12-24 23:00:00,252,partly-cloudy-night,2.79,2011-12-24 07:00:00,0.37,4.46,1028.17,2011-12-24 07:00:00,...,7.93,2011-12-24 08:06:15,2011-12-24 15:00:00,2011-12-24 13:00:00,Mostly cloudy throughout the day.,2011-12-24 19:00:00,-0.51,2011-12-24 23:00:00,2011-12-24 20:00:00,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,9.03,2014-01-26 16:00:00,233,partly-cloudy-day,2.39,2014-01-26 21:00:00,0.40,4.55,1002.10,2014-01-26 22:00:00,...,9.03,2014-01-26 07:48:49,2014-01-26 16:00:00,2014-01-26 11:00:00,Mostly cloudy until evening.,2014-01-27 05:00:00,-1.30,2014-01-26 15:00:00,2014-01-27 04:00:00,0.84
878,10.31,2014-02-27 14:00:00,224,partly-cloudy-day,3.08,2014-02-27 23:00:00,0.32,4.14,1007.02,2014-02-27 22:00:00,...,10.31,2014-02-27 06:51:45,2014-02-27 14:00:00,2014-02-27 12:00:00,Partly cloudy until evening.,2014-02-28 02:00:00,1.41,2014-02-27 14:00:00,2014-02-28 02:00:00,0.93
879,18.97,2014-03-09 14:00:00,172,partly-cloudy-night,4.30,2014-03-09 07:00:00,0.04,2.78,1022.44,2014-03-09 07:00:00,...,18.97,2014-03-09 06:29:49,2014-03-09 14:00:00,2014-03-09 12:00:00,Partly cloudy in the evening.,2014-03-10 05:00:00,7.08,2014-03-09 14:00:00,2014-03-10 06:00:00,0.28
880,8.83,2014-02-12 16:00:00,210,wind,1.94,2014-02-12 01:00:00,0.59,7.24,994.27,2014-02-12 01:00:00,...,8.83,2014-02-12 07:21:44,2014-02-12 16:00:00,2014-02-12 10:00:00,Mostly cloudy until evening and breezy through...,2014-02-13 05:00:00,-1.20,2014-02-12 16:00:00,2014-02-13 02:00:00,0.42
881,9.90,2014-02-15 12:00:00,233,wind,2.95,2014-02-15 23:00:00,0.35,9.96,988.63,2014-02-15 23:00:00,...,9.90,2014-02-15 07:16:06,2014-02-15 12:00:00,2014-02-15 10:00:00,Windy and mostly cloudy until afternoon.,2014-02-16 07:00:00,1.77,2014-02-15 12:00:00,2014-02-16 07:00:00,0.52

In [43]:
weather_daily_darksky.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   temperatureMax               882 non-null    float64
 1   temperatureMaxTime           882 non-null    object
 2   windBearing                  882 non-null    int64
 3   icon                         882 non-null    object
 4   dewPoint                     882 non-null    float64
 5   temperatureMinTime           882 non-null    object
 6   cloudCover                   881 non-null    float64
 7   windSpeed                    882 non-null    float64
 8   pressure                     882 non-null    float64
 9   apparentTemperatureMinTime   882 non-null    object
 10  apparentTemperatureHigh      882 non-null    float64
 11  precipType                   882 non-null    object
 12  visibility                   882 non-null    float64
 13  humidity                     882 non-null    float64
 14  apparentTemperatureHighTime  882 non-null    object
 15  apparentTemperatureLow       882 non-null    float64
 16  apparentTemperatureMax       882 non-null    float64
 17  uvIndex                      881 non-null    float64
 18  time                         882 non-null    object
 19  sunsetTime                   882 non-null    object
 20  temperatureLow               882 non-null    float64
 21  temperatureMin               882 non-null    float64
 22  temperatureHigh              882 non-null    float64
 23  sunriseTime                  882 non-null    object
 24  temperatureHighTime          882 non-null    object
 25  uvIndexTime                  881 non-null    object
 26  summary                      882 non-null    object
 27  temperatureLowTime           882 non-null    object
 28  apparentTemperatureMin       882 non-null    float64
 29  apparentTemperatureMaxTime   882 non-null    object
 30  apparentTemperatureLowTime   882 non-null    object
 31  moonPhase                    882 non-null    float64
dtypes: float64(16), int64(1), object(15)
memory usage: 220.6+ KB

In [28]:
print(weather_daily_darksky.columns.tolist())

['temperatureMax', 'temperatureMaxTime', 'windBearing', 'icon', 'dewPoint', 'temperatureMinTime', 'cloudCover', 'windSpeed', 'pressure', 'apparentTemperatureMinTime', 'apparentTemperatureHigh', 'precipType', 'visibility', 'humidity', 'apparentTemperatureHighTime', 'apparentTemperatureLow', 'apparentTemperatureMax', 'uvIndex', 'time', 'sunsetTime', 'temperatureLow', 'temperatureMin', 'temperatureHigh', 'sunriseTime', 'temperatureHighTime', 'uvIndexTime', 'summary', 'temperatureLowTime', 'apparentTemperatureMin', 'apparentTemperatureMaxTime', 'apparentTemperatureLowTime', 'moonPhase']

['temperatureMax', 'temperatureMaxTime', 'windBearing', 'icon', 'dewPoint', 'temperatureMinTime', 'cloudCover', 'windSpeed', 'pressure', 'apparentTemperatureMinTime', 'apparentTemperatureHigh', 'precipType', 'visibility', 'humidity', 'apparentTemperatureHighTime', 'apparentTemperatureLow', 'apparentTemperatureMax', 'uvIndex', 'time', 'sunsetTime', 'temperatureLow', 'temperatureMin', 'temperatureHigh', 'sunriseTime', 'temperatureHighTime', 'uvIndexTime', 'summary', 'temperatureLowTime', 'apparentTemperatureMin', 'apparentTemperatureMaxTime', 'apparentTemperatureLowTime', 'moonPhase']
temperatureMax - 当天的最高气温。
temperatureMaxTime - 最高气温发生的时间。
windBearing - 风向，表示风从哪个方向吹来，通常以角度表示。
icon - 天气情况的图标代码，如晴天、多云等。
dewPoint - 露点温度，表示空气达到饱和（露水开始凝结）的温度。
temperatureMinTime - 最低气温发生的时间。
cloudCover - 云量，表示天空被云层覆盖的比例。
windSpeed - 风速。
pressure - 大气压强。
apparentTemperatureMinTime - 体感最低温度发生的时间。
apparentTemperatureHigh - 当天的最高体感温度。
precipType - 降水类型，如雨、雪。
visibility - 能见度。
humidity - 湿度。
apparentTemperatureHighTime - 最高体感温度发生的时间。
apparentTemperatureLow - 当天的最低体感温度。
apparentTemperatureMax - 当天的最高体感温度。
uvIndex - 紫外线指数。
time - 观测时间。
sunsetTime - 日落时间。
temperatureLow - 当天的最低气温。
temperatureMin - 同temperatureLow，当天的最低气温。
temperatureHigh - 当天的最高气温。
sunriseTime - 日出时间。
temperatureHighTime - 最高气温发生的时间。
uvIndexTime - 紫外线指数达到最高点的时间。
summary - 天气概况的文字描述。
temperatureLowTime - 最低气温发生的时间。
apparentTemperatureMin - 当天的最低体感温度。
apparentTemperatureMaxTime - 最高体感温度发生的时间。
apparentTemperatureLowTime - 最低体感温度发生的时间。
moonPhase - 月相。

In [21]:
# weather_hourly_darksky.csv : 包含来自 darksky api 的每小时数据。有关参数的更多详情，请参阅 api 文档。
weather_hourly_darksky = pd.read_csv('archive/weather_hourly_darksky.csv')
weather_hourly_darksky

,visibility,windBearing,temperature,time,dewPoint,pressure,apparentTemperature,windSpeed,precipType,icon,humidity,summary
0,5.97,104,10.24,2011-11-11 00:00:00,8.86,1016.76,10.24,2.77,rain,partly-cloudy-night,0.91,Partly Cloudy
1,4.88,99,9.76,2011-11-11 01:00:00,8.83,1016.63,8.24,2.95,rain,partly-cloudy-night,0.94,Partly Cloudy
2,3.70,98,9.46,2011-11-11 02:00:00,8.79,1016.36,7.76,3.17,rain,partly-cloudy-night,0.96,Partly Cloudy
3,3.12,99,9.23,2011-11-11 03:00:00,8.63,1016.28,7.44,3.25,rain,fog,0.96,Foggy
4,1.85,111,9.26,2011-11-11 04:00:00,9.21,1015.98,7.24,3.70,rain,fog,1.00,Foggy
...,...,...,...,...,...,...,...,...,...,...,...,...
21160,12.68,247,7.39,2014-02-15 19:00:00,3.06,997.07,3.91,6.08,rain,partly-cloudy-night,0.74,Partly Cloudy
21161,13.78,249,6.56,2014-02-15 20:00:00,2.76,998.15,3.03,5.61,rain,clear-night,0.77,Clear
21162,14.31,248,6.47,2014-02-15 21:00:00,2.71,999.28,3.06,5.25,rain,clear-night,0.77,Clear
21163,14.31,248,5.96,2014-02-15 22:00:00,2.69,1000.33,2.68,4.69,rain,clear-night,0.80,Clear
21164,14.31,246,5.38,2014-02-15 23:00:00,2.60,1001.25,1.77,5.09,rain,clear-night,0.82,Clear

In [29]:
print(weather_hourly_darksky.columns.tolist())

['visibility', 'windBearing', 'temperature', 'time', 'dewPoint', 'pressure', 'apparentTemperature', 'windSpeed', 'precipType', 'icon', 'humidity', 'summary']

['visibility', 'windBearing', 'temperature', 'time', 'dewPoint', 'pressure', 'apparentTemperature', 'windSpeed', 'precipType', 'icon', 'humidity', 'summary']
visibility - 能见度，通常以公里或英里为单位，表示在特定天气条件下最远可见的距离。
windBearing - 风向，表示风从哪个方向吹来。通常以角度表示，其中0度代表北风，90度代表东风，180度代表南风，270度代表西风。
temperature - 气温，通常以摄氏度或华氏度为单位，表示空气的热度。
time - 时间，数据采集的具体时间点，通常以UNIX时间戳或可读格式表示。
dewPoint - 露点温度，当空气冷却到无法容纳其中所有水蒸气时，水蒸气凝结成露水的温度。
pressure - 大气压强，表示空气的重量压在地面上的力量，通常以百帕斯卡（hPa）或毫巴（mb）为单位。
apparentTemperature - 体感温度，综合考虑风速、湿度和实际气温对人体感知温度的影响。
windSpeed - 风速，表示风的快慢，通常以每秒米数或每小时英里数表示。
precipType - 降水类型，如雨、雪、冰雹等。
icon - 天气图标的标识，用于直观表示天气状况，如晴天、多云、雨天等。
humidity - 湿度，表示空气中水蒸气的含量，通常以百分比表示。
summary - 天气概况的文字描述，提供对当前或预测天气状况的简短总结。

In [44]:
print(weather_hourly_darksky.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21165 entries, 0 to 21164
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   visibility           21165 non-null  float64
 1   windBearing          21165 non-null  int64
 2   temperature          21165 non-null  float64
 3   time                 21165 non-null  object
 4   dewPoint             21165 non-null  float64
 5   pressure             21152 non-null  float64
 6   apparentTemperature  21165 non-null  float64
 7   windSpeed            21165 non-null  float64
 8   precipType           21165 non-null  object
 9   icon                 21165 non-null  object
 10  humidity             21165 non-null  float64
 11  summary              21165 non-null  object
dtypes: float64(7), int64(1), object(4)
memory usage: 1.9+ MB
None